#!/bin/sh

i3lockmultimonitor="/home/hrushi/.dotfiles/.config/i3/i3lock-multimonitor/lock"

case "$1" in
    lock)
        "$i3lockmultimonitor"
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        "$i3lockmultimonitor" && systemctl suspend
        ;;
    hibernate)
        "$i3lockmultimonitor" && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
