#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        i3lock-wrapper -l
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        i3lock-wrapper -l && systemctl suspend
        ;;
    hibernate)
        i3lock-wrapper -l && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
