# This tmux statusbar config was created by tmuxline.vim
# on Tue, 23 Jan 2018

set -g status-justify "left"
set -g status "on"
set -g status-attr "none"
set -g message-command-bg "colour243"
set -g status-left-length "100"
set -g pane-active-border-fg "colour68"
set -g status-bg "colour237"
set -g message-command-fg "colour253"
set -g pane-border-fg "colour243"
set -g message-bg "colour243"
set -g status-left-attr "none"
set -g status-right-attr "none"
set -g status-right-length "100"
set -g message-fg "colour253"
setw -g window-status-fg "colour253"
setw -g window-status-attr "none"
setw -g window-status-activity-bg "colour237"
setw -g window-status-activity-attr "none"
setw -g window-status-activity-fg "colour68"
setw -g window-status-separator ""
setw -g window-status-bg "colour237"
set -g status-left "#[fg=colour15,bg=colour68] #S #[fg=colour68,bg=colour237,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour243,bg=colour237,nobold,nounderscore,noitalics]#[fg=colour253,bg=colour243] %Y-%m-%d  %H:%M #[fg=colour68,bg=colour243,nobold,nounderscore,noitalics]#[fg=colour15,bg=colour68]  #h "
setw -g window-status-format "#[fg=colour253,bg=colour237] #I #[fg=colour253,bg=colour237] #W "
setw -g window-status-current-format "#[fg=colour237,bg=colour243,nobold,nounderscore,noitalics]#[fg=colour253,bg=colour243] #I #[fg=colour253,bg=colour243] #W #[fg=colour243,bg=colour237,nobold,nounderscore,noitalics]"
